SELECT
    MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d")
FROM MEMBER_PROFILE AS profile
JOIN REST_REVIEW AS review
    ON review.MEMBER_ID = profile.MEMBER_ID
WHERE profile.MEMBER_ID = (
    SELECT
        MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1 )
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;