-- 코드를 입력하세요
SELECT
    auth.AUTHOR_ID,
    auth.AUTHOR_NAME,
    book.CATEGORY,
    SUM(book.PRICE * sales.SALES) AS TOTAL_SALES
FROM BOOK AS book
JOIN AUTHOR AS auth
    ON book.AUTHOR_ID = auth.AUTHOR_ID
JOIN BOOK_SALES AS sales
    ON book.BOOK_ID = sales.BOOK_ID
WHERE sales.SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;