-- 코드를 작성해주세요
SELECT
    ID,
    CASE
        WHEN NT = 1 THEN 'CRITICAL'
        WHEN NT = 2 THEN 'HIGH'
        WHEN NT = 3 THEN 'MEDIUM'
        WHEN NT = 4 THEN 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT
        ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS NT
    FROM ECOLI_DATA
    ) AS ECOLI_RESULT
ORDER BY ID ASC;